// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { InstructionErrorArrayObjFlatBuffer } from '../solana/instruction-error-array-obj-flat-buffer.js';


export class ErrInstructionErrorFlatBuffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ErrInstructionErrorFlatBuffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsErrInstructionErrorFlatBuffer(bb:flatbuffers.ByteBuffer, obj?:ErrInstructionErrorFlatBuffer):ErrInstructionErrorFlatBuffer {
  return (obj || new ErrInstructionErrorFlatBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsErrInstructionErrorFlatBuffer(bb:flatbuffers.ByteBuffer, obj?:ErrInstructionErrorFlatBuffer):ErrInstructionErrorFlatBuffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ErrInstructionErrorFlatBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

instructionError(index: number, obj?:InstructionErrorArrayObjFlatBuffer):InstructionErrorArrayObjFlatBuffer|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new InstructionErrorArrayObjFlatBuffer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

instructionErrorLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startErrInstructionErrorFlatBuffer(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addInstructionError(builder:flatbuffers.Builder, instructionErrorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, instructionErrorOffset, 0);
}

static createInstructionErrorVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startInstructionErrorVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endErrInstructionErrorFlatBuffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // InstructionError
  return offset;
}

static createErrInstructionErrorFlatBuffer(builder:flatbuffers.Builder, instructionErrorOffset:flatbuffers.Offset):flatbuffers.Offset {
  ErrInstructionErrorFlatBuffer.startErrInstructionErrorFlatBuffer(builder);
  ErrInstructionErrorFlatBuffer.addInstructionError(builder, instructionErrorOffset);
  return ErrInstructionErrorFlatBuffer.endErrInstructionErrorFlatBuffer(builder);
}
}
