// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SolanaTrxMetaFlatBuffer } from '../solana/solana-trx-meta-flat-buffer.js';
import { SolanaTrxTrxFlatBuffer } from '../solana/solana-trx-trx-flat-buffer.js';


export class SolanaTrxFlatBuffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SolanaTrxFlatBuffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSolanaTrxFlatBuffer(bb:flatbuffers.ByteBuffer, obj?:SolanaTrxFlatBuffer):SolanaTrxFlatBuffer {
  return (obj || new SolanaTrxFlatBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSolanaTrxFlatBuffer(bb:flatbuffers.ByteBuffer, obj?:SolanaTrxFlatBuffer):SolanaTrxFlatBuffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SolanaTrxFlatBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

meta(obj?:SolanaTrxMetaFlatBuffer):SolanaTrxMetaFlatBuffer|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SolanaTrxMetaFlatBuffer()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

transaction(obj?:SolanaTrxTrxFlatBuffer):SolanaTrxTrxFlatBuffer|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new SolanaTrxTrxFlatBuffer()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSolanaTrxFlatBuffer(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMeta(builder:flatbuffers.Builder, metaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, metaOffset, 0);
}

static addTransaction(builder:flatbuffers.Builder, transactionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, transactionOffset, 0);
}

static endSolanaTrxFlatBuffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
