// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class BlockData implements flatbuffers.IUnpackableObject<BlockDataT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): BlockData {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsBlockData(
    bb: flatbuffers.ByteBuffer,
    obj?: BlockData
  ): BlockData {
    return (obj || new BlockData()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsBlockData(
    bb: flatbuffers.ByteBuffer,
    obj?: BlockData
  ): BlockData {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new BlockData()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  slot(): string | null;
  slot(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  slot(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  parentSlot(): string | null;
  parentSlot(
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array | null;
  parentSlot(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  previousBlockhash(): string | null;
  previousBlockhash(
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array | null;
  previousBlockhash(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  maliciousAddresses(index: number): string;
  maliciousAddresses(
    index: number,
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array;
  maliciousAddresses(
    index: number,
    optionalEncoding?: any
  ): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(
          this.bb!.__vector(this.bb_pos + offset) + index * 4,
          optionalEncoding
        )
      : null;
  }

  maliciousAddressesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  sanctionedAddresses(index: number): string;
  sanctionedAddresses(
    index: number,
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array;
  sanctionedAddresses(
    index: number,
    optionalEncoding?: any
  ): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? this.bb!.__string(
          this.bb!.__vector(this.bb_pos + offset) + index * 4,
          optionalEncoding
        )
      : null;
  }

  sanctionedAddressesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  blacklistedAddresses(index: number): string;
  blacklistedAddresses(
    index: number,
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array;
  blacklistedAddresses(
    index: number,
    optionalEncoding?: any
  ): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset
      ? this.bb!.__string(
          this.bb!.__vector(this.bb_pos + offset) + index * 4,
          optionalEncoding
        )
      : null;
  }

  blacklistedAddressesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startBlockData(builder: flatbuffers.Builder) {
    builder.startObject(6);
  }

  static addSlot(builder: flatbuffers.Builder, slotOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, slotOffset, 0);
  }

  static addParentSlot(
    builder: flatbuffers.Builder,
    parentSlotOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(1, parentSlotOffset, 0);
  }

  static addPreviousBlockhash(
    builder: flatbuffers.Builder,
    previousBlockhashOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(2, previousBlockhashOffset, 0);
  }

  static addMaliciousAddresses(
    builder: flatbuffers.Builder,
    maliciousAddressesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(3, maliciousAddressesOffset, 0);
  }

  static createMaliciousAddressesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startMaliciousAddressesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static addSanctionedAddresses(
    builder: flatbuffers.Builder,
    sanctionedAddressesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(4, sanctionedAddressesOffset, 0);
  }

  static createSanctionedAddressesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startSanctionedAddressesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static addBlacklistedAddresses(
    builder: flatbuffers.Builder,
    blacklistedAddressesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(5, blacklistedAddressesOffset, 0);
  }

  static createBlacklistedAddressesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startBlacklistedAddressesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static endBlockData(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createBlockData(
    builder: flatbuffers.Builder,
    slotOffset: flatbuffers.Offset,
    parentSlotOffset: flatbuffers.Offset,
    previousBlockhashOffset: flatbuffers.Offset,
    maliciousAddressesOffset: flatbuffers.Offset,
    sanctionedAddressesOffset: flatbuffers.Offset,
    blacklistedAddressesOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    BlockData.startBlockData(builder);
    BlockData.addSlot(builder, slotOffset);
    BlockData.addParentSlot(builder, parentSlotOffset);
    BlockData.addPreviousBlockhash(builder, previousBlockhashOffset);
    BlockData.addMaliciousAddresses(builder, maliciousAddressesOffset);
    BlockData.addSanctionedAddresses(builder, sanctionedAddressesOffset);
    BlockData.addBlacklistedAddresses(builder, blacklistedAddressesOffset);
    return BlockData.endBlockData(builder);
  }

  unpack(): BlockDataT {
    return new BlockDataT(
      this.slot(),
      this.parentSlot(),
      this.previousBlockhash(),
      this.bb!.createScalarList<string>(
        this.maliciousAddresses.bind(this),
        this.maliciousAddressesLength()
      ),
      this.bb!.createScalarList<string>(
        this.sanctionedAddresses.bind(this),
        this.sanctionedAddressesLength()
      ),
      this.bb!.createScalarList<string>(
        this.blacklistedAddresses.bind(this),
        this.blacklistedAddressesLength()
      )
    );
  }

  unpackTo(_o: BlockDataT): void {
    _o.slot = this.slot();
    _o.parentSlot = this.parentSlot();
    _o.previousBlockhash = this.previousBlockhash();
    _o.maliciousAddresses = this.bb!.createScalarList<string>(
      this.maliciousAddresses.bind(this),
      this.maliciousAddressesLength()
    );
    _o.sanctionedAddresses = this.bb!.createScalarList<string>(
      this.sanctionedAddresses.bind(this),
      this.sanctionedAddressesLength()
    );
    _o.blacklistedAddresses = this.bb!.createScalarList<string>(
      this.blacklistedAddresses.bind(this),
      this.blacklistedAddressesLength()
    );
  }
}

export class BlockDataT implements flatbuffers.IGeneratedObject {
  constructor(
    public slot: string | Uint8Array | null = null,
    public parentSlot: string | Uint8Array | null = null,
    public previousBlockhash: string | Uint8Array | null = null,
    public maliciousAddresses: string[] = [],
    public sanctionedAddresses: string[] = [],
    public blacklistedAddresses: string[] = []
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const slot = this.slot !== null ? builder.createString(this.slot!) : 0;
    const parentSlot =
      this.parentSlot !== null ? builder.createString(this.parentSlot!) : 0;
    const previousBlockhash =
      this.previousBlockhash !== null
        ? builder.createString(this.previousBlockhash!)
        : 0;
    const maliciousAddresses = BlockData.createMaliciousAddressesVector(
      builder,
      builder.createObjectOffsetList(this.maliciousAddresses)
    );
    const sanctionedAddresses = BlockData.createSanctionedAddressesVector(
      builder,
      builder.createObjectOffsetList(this.sanctionedAddresses)
    );
    const blacklistedAddresses = BlockData.createBlacklistedAddressesVector(
      builder,
      builder.createObjectOffsetList(this.blacklistedAddresses)
    );

    return BlockData.createBlockData(
      builder,
      slot,
      parentSlot,
      previousBlockhash,
      maliciousAddresses,
      sanctionedAddresses,
      blacklistedAddresses
    );
  }
}
