// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Instruction, InstructionT } from '../block/instruction.js';

export class InnerInstruction implements flatbuffers.IUnpackableObject<InnerInstructionT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): InnerInstruction {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsInnerInstruction(
    bb: flatbuffers.ByteBuffer,
    obj?: InnerInstruction
  ): InnerInstruction {
    return (obj || new InnerInstruction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsInnerInstruction(
    bb: flatbuffers.ByteBuffer,
    obj?: InnerInstruction
  ): InnerInstruction {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new InnerInstruction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  index(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  instructions(index: number, obj?: Instruction): Instruction | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? (obj || new Instruction()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  instructionsLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startInnerInstruction(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addIndex(builder: flatbuffers.Builder, index: number) {
    builder.addFieldInt32(0, index, 0);
  }

  static addInstructions(
    builder: flatbuffers.Builder,
    instructionsOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(1, instructionsOffset, 0);
  }

  static createInstructionsVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startInstructionsVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static endInnerInstruction(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createInnerInstruction(
    builder: flatbuffers.Builder,
    index: number,
    instructionsOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    InnerInstruction.startInnerInstruction(builder);
    InnerInstruction.addIndex(builder, index);
    InnerInstruction.addInstructions(builder, instructionsOffset);
    return InnerInstruction.endInnerInstruction(builder);
  }

  unpack(): InnerInstructionT {
    return new InnerInstructionT(
      this.index(),
      this.bb!.createObjList<Instruction, InstructionT>(
        this.instructions.bind(this),
        this.instructionsLength()
      )
    );
  }

  unpackTo(_o: InnerInstructionT): void {
    _o.index = this.index();
    _o.instructions = this.bb!.createObjList<Instruction, InstructionT>(
      this.instructions.bind(this),
      this.instructionsLength()
    );
  }
}

export class InnerInstructionT implements flatbuffers.IGeneratedObject {
  constructor(
    public index: number = 0,
    public instructions: InstructionT[] = []
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const instructions = InnerInstruction.createInstructionsVector(
      builder,
      builder.createObjectOffsetList(this.instructions)
    );

    return InnerInstruction.createInnerInstruction(
      builder,
      this.index,
      instructions
    );
  }
}
