// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Instruction implements flatbuffers.IUnpackableObject<InstructionT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): Instruction {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsInstruction(
    bb: flatbuffers.ByteBuffer,
    obj?: Instruction
  ): Instruction {
    return (obj || new Instruction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsInstruction(
    bb: flatbuffers.ByteBuffer,
    obj?: Instruction
  ): Instruction {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new Instruction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  parsed(): string | null;
  parsed(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  parsed(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  programId(): string | null;
  programId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  programId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  program(): string | null;
  program(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  program(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  accounts(index: number): string;
  accounts(
    index: number,
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array;
  accounts(index: number, optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(
          this.bb!.__vector(this.bb_pos + offset) + index * 4,
          optionalEncoding
        )
      : null;
  }

  accountsLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  data(): string | null;
  data(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  data(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  stackHeight(): number {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
  }

  static startInstruction(builder: flatbuffers.Builder) {
    builder.startObject(6);
  }

  static addParsed(
    builder: flatbuffers.Builder,
    parsedOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(0, parsedOffset, 0);
  }

  static addProgramId(
    builder: flatbuffers.Builder,
    programIdOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(1, programIdOffset, 0);
  }

  static addProgram(
    builder: flatbuffers.Builder,
    programOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(2, programOffset, 0);
  }

  static addAccounts(
    builder: flatbuffers.Builder,
    accountsOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(3, accountsOffset, 0);
  }

  static createAccountsVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startAccountsVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4);
  }

  static addData(builder: flatbuffers.Builder, dataOffset: flatbuffers.Offset) {
    builder.addFieldOffset(4, dataOffset, 0);
  }

  static addStackHeight(builder: flatbuffers.Builder, stackHeight: number) {
    builder.addFieldInt32(5, stackHeight, 0);
  }

  static endInstruction(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createInstruction(
    builder: flatbuffers.Builder,
    parsedOffset: flatbuffers.Offset,
    programIdOffset: flatbuffers.Offset,
    programOffset: flatbuffers.Offset,
    accountsOffset: flatbuffers.Offset,
    dataOffset: flatbuffers.Offset,
    stackHeight: number
  ): flatbuffers.Offset {
    Instruction.startInstruction(builder);
    Instruction.addParsed(builder, parsedOffset);
    Instruction.addProgramId(builder, programIdOffset);
    Instruction.addProgram(builder, programOffset);
    Instruction.addAccounts(builder, accountsOffset);
    Instruction.addData(builder, dataOffset);
    Instruction.addStackHeight(builder, stackHeight);
    return Instruction.endInstruction(builder);
  }

  unpack(): InstructionT {
    return new InstructionT(
      this.parsed(),
      this.programId(),
      this.program(),
      this.bb!.createScalarList<string>(
        this.accounts.bind(this),
        this.accountsLength()
      ),
      this.data(),
      this.stackHeight()
    );
  }

  unpackTo(_o: InstructionT): void {
    _o.parsed = this.parsed();
    _o.programId = this.programId();
    _o.program = this.program();
    _o.accounts = this.bb!.createScalarList<string>(
      this.accounts.bind(this),
      this.accountsLength()
    );
    _o.data = this.data();
    _o.stackHeight = this.stackHeight();
  }
}

export class InstructionT implements flatbuffers.IGeneratedObject {
  constructor(
    public parsed: string | Uint8Array | null = null,
    public programId: string | Uint8Array | null = null,
    public program: string | Uint8Array | null = null,
    public accounts: string[] = [],
    public data: string | Uint8Array | null = null,
    public stackHeight: number = 0
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const parsed =
      this.parsed !== null ? builder.createString(this.parsed!) : 0;
    const programId =
      this.programId !== null ? builder.createString(this.programId!) : 0;
    const program =
      this.program !== null ? builder.createString(this.program!) : 0;
    const accounts = Instruction.createAccountsVector(
      builder,
      builder.createObjectOffsetList(this.accounts)
    );
    const data = this.data !== null ? builder.createString(this.data!) : 0;

    return Instruction.createInstruction(
      builder,
      parsed,
      programId,
      program,
      accounts,
      data,
      this.stackHeight
    );
  }
}
