// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AccountKey, AccountKeyT } from '../block/account-key.js';
import { Instruction, InstructionT } from '../block/instruction.js';

export class Message implements flatbuffers.IUnpackableObject<MessageT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): Message {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsMessage(bb: flatbuffers.ByteBuffer, obj?: Message): Message {
    return (obj || new Message()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsMessage(
    bb: flatbuffers.ByteBuffer,
    obj?: Message
  ): Message {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new Message()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  accountKeys(index: number, obj?: AccountKey): AccountKey | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? (obj || new AccountKey()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  accountKeysLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  instructions(index: number, obj?: Instruction): Instruction | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? (obj || new Instruction()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  instructionsLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startMessage(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addAccountKeys(
    builder: flatbuffers.Builder,
    accountKeysOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(0, accountKeysOffset, 0);
  }

  static createAccountKeysVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startAccountKeysVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static addInstructions(
    builder: flatbuffers.Builder,
    instructionsOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(1, instructionsOffset, 0);
  }

  static createInstructionsVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startInstructionsVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static endMessage(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createMessage(
    builder: flatbuffers.Builder,
    accountKeysOffset: flatbuffers.Offset,
    instructionsOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    Message.startMessage(builder);
    Message.addAccountKeys(builder, accountKeysOffset);
    Message.addInstructions(builder, instructionsOffset);
    return Message.endMessage(builder);
  }

  unpack(): MessageT {
    return new MessageT(
      this.bb!.createObjList<AccountKey, AccountKeyT>(
        this.accountKeys.bind(this),
        this.accountKeysLength()
      ),
      this.bb!.createObjList<Instruction, InstructionT>(
        this.instructions.bind(this),
        this.instructionsLength()
      )
    );
  }

  unpackTo(_o: MessageT): void {
    _o.accountKeys = this.bb!.createObjList<AccountKey, AccountKeyT>(
      this.accountKeys.bind(this),
      this.accountKeysLength()
    );
    _o.instructions = this.bb!.createObjList<Instruction, InstructionT>(
      this.instructions.bind(this),
      this.instructionsLength()
    );
  }
}

export class MessageT implements flatbuffers.IGeneratedObject {
  constructor(
    public accountKeys: AccountKeyT[] = [],
    public instructions: InstructionT[] = []
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const accountKeys = Message.createAccountKeysVector(
      builder,
      builder.createObjectOffsetList(this.accountKeys)
    );
    const instructions = Message.createInstructionsVector(
      builder,
      builder.createObjectOffsetList(this.instructions)
    );

    return Message.createMessage(builder, accountKeys, instructions);
  }
}
