// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SanctionedEntity implements flatbuffers.IUnpackableObject<SanctionedEntityT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SanctionedEntity {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSanctionedEntity(
    bb: flatbuffers.ByteBuffer,
    obj?: SanctionedEntity
  ): SanctionedEntity {
    return (obj || new SanctionedEntity()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsSanctionedEntity(
    bb: flatbuffers.ByteBuffer,
    obj?: SanctionedEntity
  ): SanctionedEntity {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SanctionedEntity()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  entity(): string | null;
  entity(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  entity(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  static startSanctionedEntity(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addEntity(
    builder: flatbuffers.Builder,
    entityOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(0, entityOffset, 0);
  }

  static endSanctionedEntity(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createSanctionedEntity(
    builder: flatbuffers.Builder,
    entityOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    SanctionedEntity.startSanctionedEntity(builder);
    SanctionedEntity.addEntity(builder, entityOffset);
    return SanctionedEntity.endSanctionedEntity(builder);
  }

  unpack(): SanctionedEntityT {
    return new SanctionedEntityT(this.entity());
  }

  unpackTo(_o: SanctionedEntityT): void {
    _o.entity = this.entity();
  }
}

export class SanctionedEntityT implements flatbuffers.IGeneratedObject {
  constructor(public entity: string | Uint8Array | null = null) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const entity =
      this.entity !== null ? builder.createString(this.entity!) : 0;

    return SanctionedEntity.createSanctionedEntity(builder, entity);
  }
}
