// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Transaction, TransactionT } from '../block/transaction.js';
import {
  TransactionMeta,
  TransactionMetaT,
} from '../block/transaction-meta.js';

export class SolanaTransaction implements flatbuffers.IUnpackableObject<SolanaTransactionT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SolanaTransaction {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSolanaTransaction(
    bb: flatbuffers.ByteBuffer,
    obj?: SolanaTransaction
  ): SolanaTransaction {
    return (obj || new SolanaTransaction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsSolanaTransaction(
    bb: flatbuffers.ByteBuffer,
    obj?: SolanaTransaction
  ): SolanaTransaction {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SolanaTransaction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  transaction(obj?: Transaction): Transaction | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? (obj || new Transaction()).__init(
          this.bb!.__indirect(this.bb_pos + offset),
          this.bb!
        )
      : null;
  }

  meta(obj?: TransactionMeta): TransactionMeta | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? (obj || new TransactionMeta()).__init(
          this.bb!.__indirect(this.bb_pos + offset),
          this.bb!
        )
      : null;
  }

  static startSolanaTransaction(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addTransaction(
    builder: flatbuffers.Builder,
    transactionOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(0, transactionOffset, 0);
  }

  static addMeta(builder: flatbuffers.Builder, metaOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, metaOffset, 0);
  }

  static endSolanaTransaction(
    builder: flatbuffers.Builder
  ): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  unpack(): SolanaTransactionT {
    return new SolanaTransactionT(
      this.transaction() !== null ? this.transaction()!.unpack() : null,
      this.meta() !== null ? this.meta()!.unpack() : null
    );
  }

  unpackTo(_o: SolanaTransactionT): void {
    _o.transaction =
      this.transaction() !== null ? this.transaction()!.unpack() : null;
    _o.meta = this.meta() !== null ? this.meta()!.unpack() : null;
  }
}

export class SolanaTransactionT implements flatbuffers.IGeneratedObject {
  constructor(
    public transaction: TransactionT | null = null,
    public meta: TransactionMetaT | null = null
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const transaction =
      this.transaction !== null ? this.transaction!.pack(builder) : 0;
    const meta = this.meta !== null ? this.meta!.pack(builder) : 0;

    SolanaTransaction.startSolanaTransaction(builder);
    SolanaTransaction.addTransaction(builder, transaction);
    SolanaTransaction.addMeta(builder, meta);

    return SolanaTransaction.endSolanaTransaction(builder);
  }
}
