// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlockData, BlockDataT } from '../block/block-data.js';
import {
  SolanaTransaction,
  SolanaTransactionT,
} from '../block/solana-transaction.js';

export class SolanaBlock implements flatbuffers.IUnpackableObject<SolanaBlockT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SolanaBlock {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSolanaBlock(
    bb: flatbuffers.ByteBuffer,
    obj?: SolanaBlock
  ): SolanaBlock {
    return (obj || new SolanaBlock()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsSolanaBlock(
    bb: flatbuffers.ByteBuffer,
    obj?: SolanaBlock
  ): SolanaBlock {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SolanaBlock()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  hash(): string | null;
  hash(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  hash(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  height(): string | null;
  height(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  height(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  network(): string | null;
  network(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  network(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  timestamp(): string | null;
  timestamp(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  timestamp(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  blockData(obj?: BlockData): BlockData | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? (obj || new BlockData()).__init(
          this.bb!.__indirect(this.bb_pos + offset),
          this.bb!
        )
      : null;
  }

  transactions(
    index: number,
    obj?: SolanaTransaction
  ): SolanaTransaction | null {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset
      ? (obj || new SolanaTransaction()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  transactionsLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startSolanaBlock(builder: flatbuffers.Builder) {
    builder.startObject(6);
  }

  static addHash(builder: flatbuffers.Builder, hashOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, hashOffset, 0);
  }

  static addHeight(
    builder: flatbuffers.Builder,
    heightOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(1, heightOffset, 0);
  }

  static addNetwork(
    builder: flatbuffers.Builder,
    networkOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(2, networkOffset, 0);
  }

  static addTimestamp(
    builder: flatbuffers.Builder,
    timestampOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(3, timestampOffset, 0);
  }

  static addBlockData(
    builder: flatbuffers.Builder,
    blockDataOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(4, blockDataOffset, 0);
  }

  static addTransactions(
    builder: flatbuffers.Builder,
    transactionsOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(5, transactionsOffset, 0);
  }

  static createTransactionsVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startTransactionsVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static endSolanaBlock(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static finishSolanaBlockBuffer(
    builder: flatbuffers.Builder,
    offset: flatbuffers.Offset
  ) {
    builder.finish(offset);
  }

  static finishSizePrefixedSolanaBlockBuffer(
    builder: flatbuffers.Builder,
    offset: flatbuffers.Offset
  ) {
    builder.finish(offset, undefined, true);
  }

  unpack(): SolanaBlockT {
    return new SolanaBlockT(
      this.hash(),
      this.height(),
      this.network(),
      this.timestamp(),
      this.blockData() !== null ? this.blockData()!.unpack() : null,
      this.bb!.createObjList<SolanaTransaction, SolanaTransactionT>(
        this.transactions.bind(this),
        this.transactionsLength()
      )
    );
  }

  unpackTo(_o: SolanaBlockT): void {
    _o.hash = this.hash();
    _o.height = this.height();
    _o.network = this.network();
    _o.timestamp = this.timestamp();
    _o.blockData =
      this.blockData() !== null ? this.blockData()!.unpack() : null;
    _o.transactions = this.bb!.createObjList<
      SolanaTransaction,
      SolanaTransactionT
    >(this.transactions.bind(this), this.transactionsLength());
  }
}

export class SolanaBlockT implements flatbuffers.IGeneratedObject {
  constructor(
    public hash: string | Uint8Array | null = null,
    public height: string | Uint8Array | null = null,
    public network: string | Uint8Array | null = null,
    public timestamp: string | Uint8Array | null = null,
    public blockData: BlockDataT | null = null,
    public transactions: SolanaTransactionT[] = []
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const hash = this.hash !== null ? builder.createString(this.hash!) : 0;
    const height =
      this.height !== null ? builder.createString(this.height!) : 0;
    const network =
      this.network !== null ? builder.createString(this.network!) : 0;
    const timestamp =
      this.timestamp !== null ? builder.createString(this.timestamp!) : 0;
    const blockData =
      this.blockData !== null ? this.blockData!.pack(builder) : 0;
    const transactions = SolanaBlock.createTransactionsVector(
      builder,
      builder.createObjectOffsetList(this.transactions)
    );

    SolanaBlock.startSolanaBlock(builder);
    SolanaBlock.addHash(builder, hash);
    SolanaBlock.addHeight(builder, height);
    SolanaBlock.addNetwork(builder, network);
    SolanaBlock.addTimestamp(builder, timestamp);
    SolanaBlock.addBlockData(builder, blockData);
    SolanaBlock.addTransactions(builder, transactions);

    return SolanaBlock.endSolanaBlock(builder);
  }
}
