// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { UiTokenAmount, UiTokenAmountT } from '../block/ui-token-amount.js';

export class TokenBalance implements flatbuffers.IUnpackableObject<TokenBalanceT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): TokenBalance {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsTokenBalance(
    bb: flatbuffers.ByteBuffer,
    obj?: TokenBalance
  ): TokenBalance {
    return (obj || new TokenBalance()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsTokenBalance(
    bb: flatbuffers.ByteBuffer,
    obj?: TokenBalance
  ): TokenBalance {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new TokenBalance()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  accountIndex(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  mint(): string | null;
  mint(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  mint(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  owner(): string | null;
  owner(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  owner(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  programId(): string | null;
  programId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  programId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  uiTokenAmount(obj?: UiTokenAmount): UiTokenAmount | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? (obj || new UiTokenAmount()).__init(
          this.bb!.__indirect(this.bb_pos + offset),
          this.bb!
        )
      : null;
  }

  static startTokenBalance(builder: flatbuffers.Builder) {
    builder.startObject(5);
  }

  static addAccountIndex(builder: flatbuffers.Builder, accountIndex: number) {
    builder.addFieldInt32(0, accountIndex, 0);
  }

  static addMint(builder: flatbuffers.Builder, mintOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, mintOffset, 0);
  }

  static addOwner(
    builder: flatbuffers.Builder,
    ownerOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(2, ownerOffset, 0);
  }

  static addProgramId(
    builder: flatbuffers.Builder,
    programIdOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(3, programIdOffset, 0);
  }

  static addUiTokenAmount(
    builder: flatbuffers.Builder,
    uiTokenAmountOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(4, uiTokenAmountOffset, 0);
  }

  static endTokenBalance(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  unpack(): TokenBalanceT {
    return new TokenBalanceT(
      this.accountIndex(),
      this.mint(),
      this.owner(),
      this.programId(),
      this.uiTokenAmount() !== null ? this.uiTokenAmount()!.unpack() : null
    );
  }

  unpackTo(_o: TokenBalanceT): void {
    _o.accountIndex = this.accountIndex();
    _o.mint = this.mint();
    _o.owner = this.owner();
    _o.programId = this.programId();
    _o.uiTokenAmount =
      this.uiTokenAmount() !== null ? this.uiTokenAmount()!.unpack() : null;
  }
}

export class TokenBalanceT implements flatbuffers.IGeneratedObject {
  constructor(
    public accountIndex: number = 0,
    public mint: string | Uint8Array | null = null,
    public owner: string | Uint8Array | null = null,
    public programId: string | Uint8Array | null = null,
    public uiTokenAmount: UiTokenAmountT | null = null
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const mint = this.mint !== null ? builder.createString(this.mint!) : 0;
    const owner = this.owner !== null ? builder.createString(this.owner!) : 0;
    const programId =
      this.programId !== null ? builder.createString(this.programId!) : 0;
    const uiTokenAmount =
      this.uiTokenAmount !== null ? this.uiTokenAmount!.pack(builder) : 0;

    TokenBalance.startTokenBalance(builder);
    TokenBalance.addAccountIndex(builder, this.accountIndex);
    TokenBalance.addMint(builder, mint);
    TokenBalance.addOwner(builder, owner);
    TokenBalance.addProgramId(builder, programId);
    TokenBalance.addUiTokenAmount(builder, uiTokenAmount);

    return TokenBalance.endTokenBalance(builder);
  }
}
