// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Message, MessageT } from '../block/message.js';

export class Transaction implements flatbuffers.IUnpackableObject<TransactionT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): Transaction {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsTransaction(
    bb: flatbuffers.ByteBuffer,
    obj?: Transaction
  ): Transaction {
    return (obj || new Transaction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsTransaction(
    bb: flatbuffers.ByteBuffer,
    obj?: Transaction
  ): Transaction {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new Transaction()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  message(obj?: Message): Message | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? (obj || new Message()).__init(
          this.bb!.__indirect(this.bb_pos + offset),
          this.bb!
        )
      : null;
  }

  signatures(index: number): string;
  signatures(
    index: number,
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array;
  signatures(
    index: number,
    optionalEncoding?: any
  ): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(
          this.bb!.__vector(this.bb_pos + offset) + index * 4,
          optionalEncoding
        )
      : null;
  }

  signaturesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startTransaction(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addMessage(
    builder: flatbuffers.Builder,
    messageOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(0, messageOffset, 0);
  }

  static addSignatures(
    builder: flatbuffers.Builder,
    signaturesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(1, signaturesOffset, 0);
  }

  static createSignaturesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startSignaturesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4);
  }

  static endTransaction(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createTransaction(
    builder: flatbuffers.Builder,
    messageOffset: flatbuffers.Offset,
    signaturesOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    Transaction.startTransaction(builder);
    Transaction.addMessage(builder, messageOffset);
    Transaction.addSignatures(builder, signaturesOffset);
    return Transaction.endTransaction(builder);
  }

  unpack(): TransactionT {
    return new TransactionT(
      this.message() !== null ? this.message()!.unpack() : null,
      this.bb!.createScalarList<string>(
        this.signatures.bind(this),
        this.signaturesLength()
      )
    );
  }

  unpackTo(_o: TransactionT): void {
    _o.message = this.message() !== null ? this.message()!.unpack() : null;
    _o.signatures = this.bb!.createScalarList<string>(
      this.signatures.bind(this),
      this.signaturesLength()
    );
  }
}

export class TransactionT implements flatbuffers.IGeneratedObject {
  constructor(
    public message: MessageT | null = null,
    public signatures: string[] = []
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const message = this.message !== null ? this.message!.pack(builder) : 0;
    const signatures = Transaction.createSignaturesVector(
      builder,
      builder.createObjectOffsetList(this.signatures)
    );

    return Transaction.createTransaction(builder, message, signatures);
  }
}
