// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import {
  InnerInstruction,
  InnerInstructionT,
} from '../block/inner-instruction.js';
import { TokenBalance, TokenBalanceT } from '../block/token-balance.js';

export class TransactionMeta implements flatbuffers.IUnpackableObject<TransactionMetaT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): TransactionMeta {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsTransactionMeta(
    bb: flatbuffers.ByteBuffer,
    obj?: TransactionMeta
  ): TransactionMeta {
    return (obj || new TransactionMeta()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsTransactionMeta(
    bb: flatbuffers.ByteBuffer,
    obj?: TransactionMeta
  ): TransactionMeta {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new TransactionMeta()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  computeUnitsConsumed(): bigint {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
  }

  err(): string | null;
  err(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  err(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  fee(): bigint {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
  }

  innerInstructions(
    index: number,
    obj?: InnerInstruction
  ): InnerInstruction | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? (obj || new InnerInstruction()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  innerInstructionsLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  logMessages(index: number): string;
  logMessages(
    index: number,
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array;
  logMessages(
    index: number,
    optionalEncoding?: any
  ): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? this.bb!.__string(
          this.bb!.__vector(this.bb_pos + offset) + index * 4,
          optionalEncoding
        )
      : null;
  }

  logMessagesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  preBalances(index: number): bigint | null {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset
      ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8)
      : BigInt(0);
  }

  preBalancesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  postBalances(index: number): bigint | null {
    const offset = this.bb!.__offset(this.bb_pos, 16);
    return offset
      ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8)
      : BigInt(0);
  }

  postBalancesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 16);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  preTokenBalances(index: number, obj?: TokenBalance): TokenBalance | null {
    const offset = this.bb!.__offset(this.bb_pos, 18);
    return offset
      ? (obj || new TokenBalance()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  preTokenBalancesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 18);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  postTokenBalances(index: number, obj?: TokenBalance): TokenBalance | null {
    const offset = this.bb!.__offset(this.bb_pos, 20);
    return offset
      ? (obj || new TokenBalance()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4
          ),
          this.bb!
        )
      : null;
  }

  postTokenBalancesLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 20);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startTransactionMeta(builder: flatbuffers.Builder) {
    builder.startObject(9);
  }

  static addComputeUnitsConsumed(
    builder: flatbuffers.Builder,
    computeUnitsConsumed: bigint
  ) {
    builder.addFieldInt64(0, computeUnitsConsumed, BigInt('0'));
  }

  static addErr(builder: flatbuffers.Builder, errOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, errOffset, 0);
  }

  static addFee(builder: flatbuffers.Builder, fee: bigint) {
    builder.addFieldInt64(2, fee, BigInt('0'));
  }

  static addInnerInstructions(
    builder: flatbuffers.Builder,
    innerInstructionsOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(3, innerInstructionsOffset, 0);
  }

  static createInnerInstructionsVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startInnerInstructionsVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static addLogMessages(
    builder: flatbuffers.Builder,
    logMessagesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(4, logMessagesOffset, 0);
  }

  static createLogMessagesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startLogMessagesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static addPreBalances(
    builder: flatbuffers.Builder,
    preBalancesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(5, preBalancesOffset, 0);
  }

  static createPreBalancesVector(
    builder: flatbuffers.Builder,
    data: bigint[]
  ): flatbuffers.Offset {
    builder.startVector(8, data.length, 8);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt64(data[i]!);
    }
    return builder.endVector();
  }

  static startPreBalancesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(8, numElems, 8);
  }

  static addPostBalances(
    builder: flatbuffers.Builder,
    postBalancesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(6, postBalancesOffset, 0);
  }

  static createPostBalancesVector(
    builder: flatbuffers.Builder,
    data: bigint[]
  ): flatbuffers.Offset {
    builder.startVector(8, data.length, 8);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt64(data[i]!);
    }
    return builder.endVector();
  }

  static startPostBalancesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(8, numElems, 8);
  }

  static addPreTokenBalances(
    builder: flatbuffers.Builder,
    preTokenBalancesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(7, preTokenBalancesOffset, 0);
  }

  static createPreTokenBalancesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startPreTokenBalancesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static addPostTokenBalances(
    builder: flatbuffers.Builder,
    postTokenBalancesOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(8, postTokenBalancesOffset, 0);
  }

  static createPostTokenBalancesVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[]
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]!);
    }
    return builder.endVector();
  }

  static startPostTokenBalancesVector(
    builder: flatbuffers.Builder,
    numElems: number
  ) {
    builder.startVector(4, numElems, 4);
  }

  static endTransactionMeta(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createTransactionMeta(
    builder: flatbuffers.Builder,
    computeUnitsConsumed: bigint,
    errOffset: flatbuffers.Offset,
    fee: bigint,
    innerInstructionsOffset: flatbuffers.Offset,
    logMessagesOffset: flatbuffers.Offset,
    preBalancesOffset: flatbuffers.Offset,
    postBalancesOffset: flatbuffers.Offset,
    preTokenBalancesOffset: flatbuffers.Offset,
    postTokenBalancesOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    TransactionMeta.startTransactionMeta(builder);
    TransactionMeta.addComputeUnitsConsumed(builder, computeUnitsConsumed);
    TransactionMeta.addErr(builder, errOffset);
    TransactionMeta.addFee(builder, fee);
    TransactionMeta.addInnerInstructions(builder, innerInstructionsOffset);
    TransactionMeta.addLogMessages(builder, logMessagesOffset);
    TransactionMeta.addPreBalances(builder, preBalancesOffset);
    TransactionMeta.addPostBalances(builder, postBalancesOffset);
    TransactionMeta.addPreTokenBalances(builder, preTokenBalancesOffset);
    TransactionMeta.addPostTokenBalances(builder, postTokenBalancesOffset);
    return TransactionMeta.endTransactionMeta(builder);
  }

  unpack(): TransactionMetaT {
    return new TransactionMetaT(
      this.computeUnitsConsumed(),
      this.err(),
      this.fee(),
      this.bb!.createObjList<InnerInstruction, InnerInstructionT>(
        this.innerInstructions.bind(this),
        this.innerInstructionsLength()
      ),
      this.bb!.createScalarList<string>(
        this.logMessages.bind(this),
        this.logMessagesLength()
      ),
      this.bb!.createScalarList<bigint>(
        this.preBalances.bind(this),
        this.preBalancesLength()
      ),
      this.bb!.createScalarList<bigint>(
        this.postBalances.bind(this),
        this.postBalancesLength()
      ),
      this.bb!.createObjList<TokenBalance, TokenBalanceT>(
        this.preTokenBalances.bind(this),
        this.preTokenBalancesLength()
      ),
      this.bb!.createObjList<TokenBalance, TokenBalanceT>(
        this.postTokenBalances.bind(this),
        this.postTokenBalancesLength()
      )
    );
  }

  unpackTo(_o: TransactionMetaT): void {
    _o.computeUnitsConsumed = this.computeUnitsConsumed();
    _o.err = this.err();
    _o.fee = this.fee();
    _o.innerInstructions = this.bb!.createObjList<
      InnerInstruction,
      InnerInstructionT
    >(this.innerInstructions.bind(this), this.innerInstructionsLength());
    _o.logMessages = this.bb!.createScalarList<string>(
      this.logMessages.bind(this),
      this.logMessagesLength()
    );
    _o.preBalances = this.bb!.createScalarList<bigint>(
      this.preBalances.bind(this),
      this.preBalancesLength()
    );
    _o.postBalances = this.bb!.createScalarList<bigint>(
      this.postBalances.bind(this),
      this.postBalancesLength()
    );
    _o.preTokenBalances = this.bb!.createObjList<TokenBalance, TokenBalanceT>(
      this.preTokenBalances.bind(this),
      this.preTokenBalancesLength()
    );
    _o.postTokenBalances = this.bb!.createObjList<TokenBalance, TokenBalanceT>(
      this.postTokenBalances.bind(this),
      this.postTokenBalancesLength()
    );
  }
}

export class TransactionMetaT implements flatbuffers.IGeneratedObject {
  constructor(
    public computeUnitsConsumed: bigint = BigInt('0'),
    public err: string | Uint8Array | null = null,
    public fee: bigint = BigInt('0'),
    public innerInstructions: InnerInstructionT[] = [],
    public logMessages: string[] = [],
    public preBalances: bigint[] = [],
    public postBalances: bigint[] = [],
    public preTokenBalances: TokenBalanceT[] = [],
    public postTokenBalances: TokenBalanceT[] = []
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const err = this.err !== null ? builder.createString(this.err!) : 0;
    const innerInstructions = TransactionMeta.createInnerInstructionsVector(
      builder,
      builder.createObjectOffsetList(this.innerInstructions)
    );
    const logMessages = TransactionMeta.createLogMessagesVector(
      builder,
      builder.createObjectOffsetList(this.logMessages)
    );
    const preBalances = TransactionMeta.createPreBalancesVector(
      builder,
      this.preBalances
    );
    const postBalances = TransactionMeta.createPostBalancesVector(
      builder,
      this.postBalances
    );
    const preTokenBalances = TransactionMeta.createPreTokenBalancesVector(
      builder,
      builder.createObjectOffsetList(this.preTokenBalances)
    );
    const postTokenBalances = TransactionMeta.createPostTokenBalancesVector(
      builder,
      builder.createObjectOffsetList(this.postTokenBalances)
    );

    return TransactionMeta.createTransactionMeta(
      builder,
      this.computeUnitsConsumed,
      err,
      this.fee,
      innerInstructions,
      logMessages,
      preBalances,
      postBalances,
      preTokenBalances,
      postTokenBalances
    );
  }
}
