// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UiTokenAmount implements flatbuffers.IUnpackableObject<UiTokenAmountT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): UiTokenAmount {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsUiTokenAmount(
    bb: flatbuffers.ByteBuffer,
    obj?: UiTokenAmount
  ): UiTokenAmount {
    return (obj || new UiTokenAmount()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsUiTokenAmount(
    bb: flatbuffers.ByteBuffer,
    obj?: UiTokenAmount
  ): UiTokenAmount {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new UiTokenAmount()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  amount(): string | null;
  amount(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  amount(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  decimals(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  uiAmount(): number {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
  }

  uiAmountString(): string | null;
  uiAmountString(
    optionalEncoding: flatbuffers.Encoding
  ): string | Uint8Array | null;
  uiAmountString(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  static startUiTokenAmount(builder: flatbuffers.Builder) {
    builder.startObject(4);
  }

  static addAmount(
    builder: flatbuffers.Builder,
    amountOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(0, amountOffset, 0);
  }

  static addDecimals(builder: flatbuffers.Builder, decimals: number) {
    builder.addFieldInt32(1, decimals, 0);
  }

  static addUiAmount(builder: flatbuffers.Builder, uiAmount: number) {
    builder.addFieldFloat64(2, uiAmount, 0.0);
  }

  static addUiAmountString(
    builder: flatbuffers.Builder,
    uiAmountStringOffset: flatbuffers.Offset
  ) {
    builder.addFieldOffset(3, uiAmountStringOffset, 0);
  }

  static endUiTokenAmount(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createUiTokenAmount(
    builder: flatbuffers.Builder,
    amountOffset: flatbuffers.Offset,
    decimals: number,
    uiAmount: number,
    uiAmountStringOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    UiTokenAmount.startUiTokenAmount(builder);
    UiTokenAmount.addAmount(builder, amountOffset);
    UiTokenAmount.addDecimals(builder, decimals);
    UiTokenAmount.addUiAmount(builder, uiAmount);
    UiTokenAmount.addUiAmountString(builder, uiAmountStringOffset);
    return UiTokenAmount.endUiTokenAmount(builder);
  }

  unpack(): UiTokenAmountT {
    return new UiTokenAmountT(
      this.amount(),
      this.decimals(),
      this.uiAmount(),
      this.uiAmountString()
    );
  }

  unpackTo(_o: UiTokenAmountT): void {
    _o.amount = this.amount();
    _o.decimals = this.decimals();
    _o.uiAmount = this.uiAmount();
    _o.uiAmountString = this.uiAmountString();
  }
}

export class UiTokenAmountT implements flatbuffers.IGeneratedObject {
  constructor(
    public amount: string | Uint8Array | null = null,
    public decimals: number = 0,
    public uiAmount: number = 0.0,
    public uiAmountString: string | Uint8Array | null = null
  ) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    const amount =
      this.amount !== null ? builder.createString(this.amount!) : 0;
    const uiAmountString =
      this.uiAmountString !== null
        ? builder.createString(this.uiAmountString!)
        : 0;

    return UiTokenAmount.createUiTokenAmount(
      builder,
      amount,
      this.decimals,
      this.uiAmount,
      uiAmountString
    );
  }
}
